Repository probcomp/metaprob, pull requests merged in 2019-04, with the labels that each got.

#131 Run ClojureScript tests in both JVM-hosted and self-hosted contexts
  Dockerfile
  Makefile
Labels: enhancement, testing

#140 Simplify Dockerfile, clean up after tests in Makefile
  Dockerfile
  Makefile
Labels: testing

#144 Pin Planck to a specific version
  Dockerfile
Labels: bug
